# Docker Compose configuration for Reshift No-Code Platform
# Alternative deployment method using Docker

version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: reshift-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-reshift}
      MYSQL_USER: ${MYSQL_USER:-reshift}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-reshift123}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - reshift-network

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    container_name: reshift-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - reshift-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: reshift-backend
    restart: unless-stopped
    environment:
      - DATABASE_URL=mysql+pymysql://${MYSQL_USER:-reshift}:${MYSQL_PASSWORD:-reshift123}@mysql:3306/${MYSQL_DATABASE:-reshift}
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=${SECRET_KEY:-your-super-secret-key}
      - ENVIRONMENT=production
      - DEBUG=false
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - redis
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    networks:
      - reshift-network

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: reshift-frontend
    restart: unless-stopped
    environment:
      - VITE_API_BASE_URL=http://localhost:8000/api/v1
      - NODE_ENV=production
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - reshift-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: reshift-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
      - ./uploads:/var/www/uploads
    depends_on:
      - frontend
      - backend
    networks:
      - reshift-network

volumes:
  mysql_data:
  redis_data:

networks:
  reshift-network:
    driver: bridge
